apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    type: my-pod
spec:
  containers:
  - name: client
    image: praqma/network-multitool
    command: ["bin/sh", "-c", "sleep 10000"] 
  nodeName: k8s1
